### ISSUE TITLE
Setup Gorm in the Go backend

### ISSUE THREAD

**Issue by Connor-Thorpe01** [cs481-ekh/s24-illiterate-librarians#103]
references #102

**Comment by Connor-Thorpe01** [comment]
[t:120] added models for all tables

**Comment by ALackey-ai** [comment]
added model for the applications table based on updated schema 
[t:45]

**Comment by ALackey-ai** [comment]
Did some research on how to use gorm to query the database table for things and to update/add entries.
[t:15]
