### ISSUE TITLE
Users can update their info through the profile page

### ISSUE THREAD

**Issue by ryesing** [cs481-ekh/s24-illiterate-librarians#155]

**Comment by ryesing** [comment]
[t:60]
Working with Docker and setting up the database as well as my .env file

**Comment by ryesing** [comment]
[t:75]
Working on turning my form into an angular form

**Comment by ryesing** [comment]
[t180]
Worked on getting the parent page of the profile to talk to the backend, most of the stuff is close to being there, need to get the handlers done before i can completely finish

**Comment by ryesing** [comment]
[t:360]
I know this is a big time chunk but it incorporates all of the time i have worked on this in sprint 4 which was over several days and also included creating the code to get the data from the back end

**Comment by AndrewDoering01** [comment]
[t:60]

Fixed validators

**Comment by ryesing** [comment]
[t:60]
Helped with fixing validators
