### ISSUE TITLE
adding  automated emails

### ISSUE THREAD

**Issue by ALackey-ai** [cs481-ekh/s24-illiterate-librarians#212]
As a instructor, I want to create a message so that I can have it be emailed to everyone

## Definition of Done
- [ ] email automations are setup and tested

## Tasks
- [ ] Setup email automation and test it

**Comment by ALackey-ai** [comment]
Created a new gmail, figured out how to setup the security of it, and then finally got emails to work, without them being spam either! 

[t:160]

**Comment by ALackey-ai** [comment]
Tried to figure out how to setup my env file to hold the sensitive data/passwords but let the handler still have access to them. haven't been successful yet but I'll try again later today.

[t:20]

**Comment by Connor-Thorpe01** [comment]
[t:60] wrote dao and helped set it up

**Comment by ALackey-ai** [comment]
finished the handler and tested it
[t:45]
